routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\BoardUserController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskUserController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\AttachmentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

// Route::get('login',function(){
//     return "connection";
// })-> name('login');


Route::resource('categories', CategoryController::class)->middleware('auth');

Route::get('dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// Route::get('boards',[BoardController::class, 'index'])->middleware('auth')->name('boards.index');
// Route::get('boards/create',[BoardController::class, 'create'])->middleware('auth')->name('boards.create');
// Route::post('boards/',[BoardController::class, 'store'])->middleware('auth')->name('boards.store');
// Route::get('boards/{board}',[BoardController::class, 'show'])->middleware('auth')->name('boards.show');
// Route::get('boards/{board}/edit',[BoardController::class, 'edit'])->middleware('auth')->name('boards.edit');
// Route::put('boards/{board}',[BoardController::class, 'update'])->middleware('auth')->name('boards.update');
// Route::delete('boards/{board}',[BoardController::class, 'destroy'])->middleware('auth')->name('boards.destroy');

Route::resource('boards', BoardController::class)->middleware('auth');

Route::get('boards/{board}/boardUser/create',[BoardUserController::class, 'create'])->middleware('auth')->name('boards.boardUser.create');
Route::post('boards/{board}/boardUser',[BoardUserController::class, 'store'])->middleware('auth')->name('boards.boardUser.store');
Route::delete('boardUser/{boardUser}',[BoardUserController::class, 'destroy'])->middleware('auth')->name('boardUser.destroy');

Route::get('boards/{board}/tasks/create',[TaskController::class, 'create'])->middleware('auth')->name('boards.tasks.create');
Route::post('boards/{board}/task',[TaskController::class, 'store'])->middleware('auth')->name('boards.tasks.store');
Route::get('tasks/{task}',[TaskController::class, 'show'])->middleware('auth')->name('tasks.show');
Route::get('tasks/{task}/edit',[TaskController::class, 'edit'])->middleware('auth')->name('tasks.edit');
Route::put('tasks/{task}',[TaskController::class, 'update'])->middleware('auth')->name('tasks.update');
Route::delete('tasks/{task}',[TaskController::class, 'destroy'])->middleware('auth')->name('tasks.destroy');

Route::get('tasks/{task}/taskUser/create',[TaskUserController::class, 'create'])->middleware('auth')->name('tasks.taskUser.create');
Route::post('tasks/{task}/taskUser',[TaskUserController::class, 'store'])->middleware('auth')->name('tasks.taskUser.store');
Route::delete('taskUser/{taskUser}',[TaskUserController::class, 'destroy'])->middleware('auth')->name('taskUser.destroy');

Route::post('tasks/{task}/comments',[CommentController::class, 'store'])->middleware('auth')->name('tasks.comments.store');
Route::put('comments/{comment}',[CommentController::class, 'update'])->middleware('auth')->name('tasks.comments.update');
Route::delete('comments/{comment}',[CommentController::class, 'destroy'])->middleware('auth')->name('comments.destroy');

Route::post('tasks/{task}/attachments',[AttachmentController::class, 'store'])->middleware('auth')->name('tasks.attachments.store');
Route::put('attachments/{attachment}',[AttachmentController::class, 'update'])->middleware('auth')->name('tasks.attachments.update');
Route::delete('attachments/{attachment}',[AttachmentController::class, 'destroy'])->middleware('auth')->name('attachments.destroy');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Le modèle Category qui est lié à la table categories dans la base de données
 * 
 * @author Clara Vesval B2B Info <clara.vesval@ynov.com>
 * 
 */

class Category extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable=["name"];

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    
    /**
     * Renvoi la liste des tâches possédant cette catégorie
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */

    public function tasks()
{
    return $this->hasMany('App\Models\Task');
}
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Contracts\Session\Session;
use Illuminate\Http\Request;

/**
 * Controller pour le CRUD Category
 * 
 * @author Clara Vesval B2B Info <clara.vesval@ynov.com>
 * 
 */

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories= Category::all();
        return view('category.index', ['categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validateData= $request->validate([
            'name'=>'required|min:6|unique:categories',
        ]);
        $category=new Category();
        $category->name = $validateData["name"];
        $category->save();
        return redirect('/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
        return view('category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        return view('category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
        $validateData= $request->validate([
            'name'=>'required|min:6|unique:categories',
        ]);
        $category->update(['name'=>$validateData["name"]]);
        return redirect('/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
        $category->delete();
        return redirect('/categories');
    }
}

resources/views/category/create.blade.php
@extends('layouts.main')

@section('title', 'Create a category')

@section ('content')
<form method="POST" action="/categories">
    @csrf
    
    <label for='name'> Category Name </label>
    <input type="text" id="name" name="name" class=@error('name') is-invalid @enderror>

    @error('name')
    <div class="alert alert-danger"> {{$message}} </div>
    @enderror 
    <button type="submit"> Sauvegarder </button>

</form>

<div class="row">
    <a class="btn btn-primary m-auto" href="{{route('categories.index')}}"> Retour </a>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.main')

@section('title', 'Update a category')

@section ('content')

<form method="POST" action="{{route('categories.update',$category->id)}}">
    @csrf
    @method('PATCH')
    <div class="form-group">
    <label for='name'> Category Name </label>
    <input type="text" value={{$category->name}} id="name" name="name" class=@error('name') is-invalid @enderror>
</div>
    @error('name')
    <div class="alert alert-danger"> {{$message}} </div>
    @enderror 
    <button type="submit"> Sauvegarder </button>
</form>

<div class="row">
    <a class="btn btn-primary m-auto" href="{{route('categories.index')}}"> Retour </a>
    </div>

@endsection

resources/views/category/index.blade.php
@extends('layouts.main')

@section('title', 'Display a category')

@section ('content')

<table class="table">
<tr>
    <td>ID</td>
    <td>Name</td>
    <td>Actions</td>
</tr>
@foreach ($categories as $category)
    <tr>
        <td>{{$category->id}}</td>
        <td>{{$category->name}}</td>
        <td> <a class="btn btn-info" href="{{route('categories.show',$category->id)}}"> Voir</a></td>
        <td> <a class="btn btn-success" href="{{route('categories.edit',$category->id)}}"> Modifer</a></td>
        <td> <form action="{{route('categories.destroy',$category->id)}}" method="post">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger" type="submit"> Supprimer </button>
    </form>
        </td>
    </tr>
@endforeach
</table>

<a class="btn btn-primary" href="{{route('categories.create')}}"> Ajouter une catégorie</a>
<br/><br/>

<div class="row">
<a class="btn btn-primary m-auto" href="{{route('boards.index')}}"> Retour </a>
</div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.main')

@section('title', 'Display a category')

@section ('content')
<p> Ma catégorie à l'id : {{$category->id}}</p>
<p> Ma catégorie s'appelle : {{$category->name}}</p>
<p> Ma catégorie à été crée le : {{$category->created_at}}</p>
<p> Ma catégorie à été modifié le : {{$category->updated_at}}</p>

<div class="row">
    <a class="btn btn-primary m-auto" href="{{route('categories.index')}}"> Retour </a>
    </div>

@endsection